comparisons_file: comparisons.tsv
design_formula: "~ sex + condition2" #"~ Reprogrammation + Age + sex + condition2"
gene_expression_xlsx: "data/gene_expression.xlsx"
coldata_xlsx: "data/RNAseq_proteomics_info.xlsx"
merge_replicates: false
lfc_threshold: 0.5
lfc: 2
bm: 50
lfcse: 1
samples_to_exclude:
  - WT3
  - DMD9
